In [3]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [5]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [8]:
df = pd.read_csv('emails.csv')
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
df.shape

(5728, 2)

In [10]:
df.columns

Index(['text', 'spam'], dtype='object')

In [11]:
df.drop_duplicates(inplace = True)

In [12]:
df.shape

(5695, 2)

In [13]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [14]:
nltk.download ('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
def process_text(text):
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  return clean_words


In [19]:
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [31]:
msg4 = 'hello google hello hello google play'
msg5 = 'code code code untill hello'
print(msg4)
print()

hello google hello hello google play



In [34]:
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[msg4],[msg5]])
print(bow4)
print()

print(bow4.shape)

  (0, 2)	3
  (0, 1)	2
  (0, 3)	1
  (1, 2)	1
  (1, 0)	3
  (1, 4)	1

(2, 5)


In [35]:
from sklearn.feature_extraction.text import CountVectorizer
msg_bow = CountVectorizer(analyzer= process_text).fit_transform(df['text'])

In [38]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test = train_test_split(msg_bow,df['spam'], test_size=0.20, random_state = 0)|

SyntaxError: ignored

In [39]:
msg_bow.shape

(5695, 37229)

In [40]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train,y_train)

In [41]:
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [44]:
print(y_train.values)

[0 0 0 ... 0 0 0]


In [46]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))
print()

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556




In [48]:
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()

Confusion Matrix: 
 [[3445   12]
 [   1 1098]]



In [49]:
from nltk.metrics.scores import accuracy
print('Accuracy: ',accuracy_score(y_train,pred))

Accuracy:  0.9971466198419666


In [51]:
print(classifier.predict(x_test))
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [53]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
from nltk.metrics.scores import accuracy
print('Accuracy: ',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]

Accuracy:  0.9920983318700615
